In [ ]:
box_params = {0: [110, 406, 7, 312620, 242], 1: [76, 406, 10, 308560, 356], 2: [76, 406, 7, 215992, 460], 3: [110, 18, 10, 19800, 61], 4: [110, 18, 7, 13860, 168], 5: [110, 9, 24, 23760, 183], 6: [110, 9, 24, 23760, 184], 7: [110, 388, 5, 213400, 200], 8: [34, 234, 17, 135252, 286], 9: [110, 82, 19, 171380, 383], 10: [78, 85, 17, 112710, 416], 11: [78, 69, 17, 91494, 383], 
12: [76, 234, 10, 177840, 414], 13: [76, 234, 7, 124488, 106], 14: [110, 181, 19, 378290, 128], 15: [32, 154, 9, 44352, 415], 16: [32, 154, 8, 39424, 486], 17: [6, 406, 17, 41412, 495], 18: [47, 125, 19, 111625, 349], 19: [63, 125, 11, 86625, 275], 20: [63, 125, 8, 63000, 380], 21: [28, 340, 17, 161840, 144], 22: [28, 66, 17, 31416, 183]}
box_params.items()

dict_items([(0, [110, 406, 7, 312620, 242]), (1, [76, 406, 10, 308560, 356]), (2, [76, 406, 7, 215992, 460]), (3, [110, 18, 10, 19800, 61]), (4, [110, 18, 7, 13860, 168]), (5, [110, 9, 24, 23760, 183]), (6, [110, 9, 24, 23760, 184]), (7, [110, 388, 5, 213400, 200]), (8, [34, 234, 17, 135252, 286]), (9, [110, 82, 19, 171380, 383]), (10, [78, 85, 17, 112710, 416]), (11, [78, 69, 17, 91494, 383]), (12, [76, 234, 10, 177840, 414]), (13, [76, 234, 7, 124488, 106]), (14, [110, 181, 19, 378290, 128]), (15, [32, 154, 9, 44352, 415]), (16, [32, 154, 8, 39424, 486]), (17, [6, 406, 17, 41412, 495]), (18, [47, 125, 19, 111625, 349]), (19, [63, 125, 11, 86625, 275]), (20, [63, 125, 8, 63000, 380]), (21, [28, 340, 17, 161840, 144]), (22, [28, 66, 17, 31416, 183])])

In [1]:
def printi(x):
    print(x)
    #print(x[1],x[1][0],x[1][1],x[1][2],x[1][3],x[1][4])
# x=5
# for i in range(0, x):
sorted(box_params.items(), key=printi)#key=lambda xx: xx[1][i])

NameError: name 'box_params' is not defined

In [7]:
def printi(x):
    print(x[1][0])
    #print(x[1],x[1][0],x[1][1],x[1][2],x[1][3],x[1][4])
# x=5
# for i in range(0, x):
sorted(box_params.items(), key=printi)#key=lambda xx: xx[1][i])

110
76
76
110
110
110
110
110
34
110
78
78
76
76
110
32
32
6
47
63
63
28
28


TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'

In [10]:
from pprint import pprint
x=5
for i in range(0, x):
    print(f"iter{i}")
    pprint(sorted(box_params.items(), key=lambda xx: xx[1][i]))
    #sorted_box = dict(sorted(box_params.items(), key=lambda xx: xx[1][i]))
    print()

iter0
[(17, [6, 406, 17, 41412, 495]),
 (21, [28, 340, 17, 161840, 144]),
 (22, [28, 66, 17, 31416, 183]),
 (15, [32, 154, 9, 44352, 415]),
 (16, [32, 154, 8, 39424, 486]),
 (8, [34, 234, 17, 135252, 286]),
 (18, [47, 125, 19, 111625, 349]),
 (19, [63, 125, 11, 86625, 275]),
 (20, [63, 125, 8, 63000, 380]),
 (1, [76, 406, 10, 308560, 356]),
 (2, [76, 406, 7, 215992, 460]),
 (12, [76, 234, 10, 177840, 414]),
 (13, [76, 234, 7, 124488, 106]),
 (10, [78, 85, 17, 112710, 416]),
 (11, [78, 69, 17, 91494, 383]),
 (0, [110, 406, 7, 312620, 242]),
 (3, [110, 18, 10, 19800, 61]),
 (4, [110, 18, 7, 13860, 168]),
 (5, [110, 9, 24, 23760, 183]),
 (6, [110, 9, 24, 23760, 184]),
 (7, [110, 388, 5, 213400, 200]),
 (9, [110, 82, 19, 171380, 383]),
 (14, [110, 181, 19, 378290, 128])]

iter1
[(5, [110, 9, 24, 23760, 183]),
 (6, [110, 9, 24, 23760, 184]),
 (3, [110, 18, 10, 19800, 61]),
 (4, [110, 18, 7, 13860, 168]),
 (22, [28, 66, 17, 31416, 183]),
 (11, [78, 69, 17, 91494, 383]),
 (9, [110, 82, 19, 17

In [11]:
from pprint import pprint
x=5
for i in range(0, x):
    print(f"iter{i}")
    #pprint(sorted(box_params.items(), key=lambda xx: xx[1][i]))
    sorted_box = dict(sorted(box_params.items(), key=lambda xx: xx[1][i]))
    pprint(sorted_box)
    print()

iter0
{0: [110, 406, 7, 312620, 242],
 1: [76, 406, 10, 308560, 356],
 2: [76, 406, 7, 215992, 460],
 3: [110, 18, 10, 19800, 61],
 4: [110, 18, 7, 13860, 168],
 5: [110, 9, 24, 23760, 183],
 6: [110, 9, 24, 23760, 184],
 7: [110, 388, 5, 213400, 200],
 8: [34, 234, 17, 135252, 286],
 9: [110, 82, 19, 171380, 383],
 10: [78, 85, 17, 112710, 416],
 11: [78, 69, 17, 91494, 383],
 12: [76, 234, 10, 177840, 414],
 13: [76, 234, 7, 124488, 106],
 14: [110, 181, 19, 378290, 128],
 15: [32, 154, 9, 44352, 415],
 16: [32, 154, 8, 39424, 486],
 17: [6, 406, 17, 41412, 495],
 18: [47, 125, 19, 111625, 349],
 19: [63, 125, 11, 86625, 275],
 20: [63, 125, 8, 63000, 380],
 21: [28, 340, 17, 161840, 144],
 22: [28, 66, 17, 31416, 183]}

iter1
{0: [110, 406, 7, 312620, 242],
 1: [76, 406, 10, 308560, 356],
 2: [76, 406, 7, 215992, 460],
 3: [110, 18, 10, 19800, 61],
 4: [110, 18, 7, 13860, 168],
 5: [110, 9, 24, 23760, 183],
 6: [110, 9, 24, 23760, 184],
 7: [110, 388, 5, 213400, 200],
 8: [34, 234, 

In [12]:
from operator import itemgetter


inventory = [('apple', 3), ('banana', 2), ('pear', 5), ('orange', 1)]
getcount = itemgetter(1)




In [14]:
print(getcount)

operator.itemgetter(1)


In [18]:
import numpy as np
position3d = [34, 0, 14]
size = [76, 406, 10]
cube = np.array([[0, 0, 0],
                     [1, 0, 0],
                     [1, 1, 0],
                     [0, 1, 0],
                     [0, 0, 1],
                     [1, 0, 1],
                     [1, 1, 1],
                     [0, 1, 1]], dtype=float) 
cube *= np.asarray(size)  # scale the cube to get the vertices of a parallelipipedic bar
print(cube)
print()
cube += np.asarray(position3d)  # translate each  bar on the directio OP, with P=position3d
print(cube)

[[  0.   0.   0.]
 [ 76.   0.   0.]
 [ 76. 406.   0.]
 [  0. 406.   0.]
 [  0.   0.  10.]
 [ 76.   0.  10.]
 [ 76. 406.  10.]
 [  0. 406.  10.]]

[[ 34.   0.  14.]
 [110.   0.  14.]
 [110. 406.  14.]
 [ 34. 406.  14.]
 [ 34.   0.  24.]
 [110.   0.  24.]
 [110. 406.  24.]
 [ 34. 406.  24.]]


In [19]:
array([[  0.,   0.,   0.],
       [110.,   0.,   0.],
       [110., 406.,   0.],
       [  0., 406.,   0.],
       [  0.,   0.,   7.],
       [110.,   0.,   7.],
       [110., 406.,   7.],
       [  0., 406.,   7.]])
array([[ 34.,   0.,  14.],
       [110.,   0.,  14.],
       [110., 406.,  14.],
       [ 34., 406.,  14.],
       [ 34.,   0.,  24.],
       [110.,   0.,  24.],
       [110., 406.,  24.],
       [ 34., 406.,  24.]])
array([[ 34.,   0.,   7.],
       [110.,   0.,   7.],
       [110., 406.,   7.],
       [ 34., 406.,   7.],
       [ 34.,   0.,  14.],
       [110.,   0.,  14.],
       [110., 406.,  14.],
       [ 34., 406.,  14.]])
[0, 88, 0, 63, 0, 23, 63, 88, 22, 89, 23, 63]
[62, 22, 1, 62, 22, 1, 62, 89, 23, 88, 1, 89]
[88, 0, 63, 0, 23, 0, 88, 63, 89, 22, 63, 23]
array([ 0, 62, 88, 22,  1, 63, 89, 23, 43, 64, 90, 51, 44, 65, 91, 52, 42,
       63, 89, 50, 43, 64, 90, 51,  3, 66, 73, 10,  4, 67, 74, 12,  2, 65,
       71,  8,  3, 66, 73, 10,  6, 69, 74, 12,  7, 70, 76, 14,  4, 67, 69,
        6,  5, 68, 70,  7,  8, 71, 91, 24,  9, 72, 92, 25, 17, 47, 53, 25,
       19, 49, 55, 26, 13, 75, 79, 15, 14, 76, 81, 16, 37, 77, 82, 39, 38,
       78, 84, 41, 34, 72, 77, 37, 36, 75, 78, 38, 48, 83, 93, 54, 49, 84,
       94, 55, 47, 82, 92, 53, 48, 83, 93, 54, 20, 85, 94, 26, 21, 87, 95,
       27, 11, 35, 40, 18, 13, 36, 41, 19,  9, 34, 39, 17, 11, 35, 40, 18,
        1, 28, 32, 23,  2, 29, 33, 24, 15, 56, 59, 20, 16, 58, 61, 21, 57,
       80, 86, 60, 58, 81, 87, 61, 56, 79, 85, 59, 57, 80, 86, 60, 30, 45,
       50, 32, 31, 46, 52, 33, 28, 42, 45, 30, 29, 44, 46, 31],
      dtype=int64)

(8, 3)

In [22]:
I,J,k=0,0,0
i=[8 * k, 8 * k + 2, 8 * k, 8 * k + 5, 8 * k, 8 * k + 7, 8 * k + 5, 8 * k + 2, 8 * k + 3,
                               8 * k + 6, 8 * k + 7, 8 * k + 5]
j=[8 * k + 1, 8 * k + 3, 8 * k + 4, 8 * k + 1, 8 * k + 3, 8 * k + 4, 8 * k + 1, 8 * k + 6,
                               8 * k + 7, 8 * k + 2, 8 * k + 4, 8 * k + 6]
k=[8 * k + 2, 8 * k, 8 * k + 5, 8 * k, 8 * k + 7, 8 * k, 8 * k + 2, 8 * k + 5, 8 * k + 6,
                               8 * k + 3, 8 * k + 5, 8 * k + 7]
print(i)
print(j)
print(k)

[0, 2, 0, 5, 0, 7, 5, 2, 3, 6, 7, 5]
[1, 3, 4, 1, 3, 4, 1, 6, 7, 2, 4, 6]
[2, 0, 5, 0, 7, 0, 2, 5, 6, 3, 5, 7]
